---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tetragon-pdb
  namespace: kube-system
  labels:
    app.kubernetes.io/name: tetragon
    app.kubernetes.io/instance: tetragon
    app.kubernetes.io/component: agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: tetragon
      app.kubernetes.io/name: tetragon
  minAvailable: 1
