apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetragon-policies
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/gccloudone-aurora/tetragon-policies.git'
    targetRevision: HEAD
    path: policies/configuration
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
