apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tetragon-logs
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-premium
