apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tetragon-agent
  namespace: TETRAGON_NAMESPACE
spec:
  minAvailable: PDB_MIN_AVAILABLE
  selector:
    matchLabels:
      app.kubernetes.io/name: tetragon
