apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: STORAGE_PVC_NAME
  namespace: TETRAGON_NAMESPACE
spec:
  accessModes:
    - STORAGE_ACCESS_MODE
  resources:
    requests:
      storage: STORAGE_SIZE
  storageClassName: STORAGE_CLASS_NAME
