apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tetragon-agent
  namespace: PROMETHEUS_NAMESPACE
  labels:
    release: PROMETHEUS_RELEASE_LABEL
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tetragon
  namespaceSelector:
    matchNames:
      - TETRAGON_NAMESPACE
  endpoints:
    - port: METRICS_PORT
      interval: SCRAPE_INTERVAL
