apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- filename_monitoring_filtered.yaml
- lsm_bprm_check.yaml
- lsm_file_open.yaml
- privileges-raise.yaml
- process-creds-changed.yaml
- process-exec-elf-begin.yaml
- process.credentials.changes.at.syscalls.yaml
- security_bprm_check.yaml
