name: Validate kustomize

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'latest'
    - name: Validate kustomize build and dry-run
      run: |
        kubectl kustomize . > out.yaml
        kubectl apply --dry-run=client -f out.yaml
